// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/media_model.dart';
import 'model/photo_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 343638898507321583),
      name: 'Photo',
      lastPropertyId: const obx_int.IdUid(4, 1098208634247936322),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5046721595999402472),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6488674444194304565),
            name: 'captureDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1098208634247936322),
            name: 'galleryId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4166876266755976682),
      name: 'Media',
      lastPropertyId: const obx_int.IdUid(10, 6888638822771786344),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6567032572261037844),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7944187188132686087),
            name: 'path',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8058876595369739984),
            name: 'isVideo',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6361498806110048278),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5022621848819639854),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9118262124126547053),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1309076990501241707),
            name: 'galleryId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8164913300386545428),
            name: 'mediaStoreId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1626538339423415469),
            name: 'width',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6888638822771786344),
            name: 'height',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 4166876266755976682),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [8979508244799148215],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Photo: obx_int.EntityDefinition<Photo>(
        model: _entities[0],
        toOneRelations: (Photo object) => [],
        toManyRelations: (Photo object) => {},
        getId: (Photo object) => object.id,
        setId: (Photo object, int id) {
          object.id = id;
        },
        objectToFB: (Photo object, fb.Builder fbb) {
          final galleryIdOffset = fbb.writeString(object.galleryId);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(2, object.captureDate.millisecondsSinceEpoch);
          fbb.addOffset(3, galleryIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final galleryIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final captureDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final object = Photo(
              id: idParam,
              galleryId: galleryIdParam,
              captureDate: captureDateParam);

          return object;
        }),
    Media: obx_int.EntityDefinition<Media>(
        model: _entities[1],
        toOneRelations: (Media object) => [],
        toManyRelations: (Media object) => {},
        getId: (Media object) => object.id,
        setId: (Media object, int id) {
          object.id = id;
        },
        objectToFB: (Media object, fb.Builder fbb) {
          final pathOffset = fbb.writeString(object.path);
          final addressOffset = fbb.writeString(object.address);
          final galleryIdOffset = object.galleryId == null
              ? null
              : fbb.writeString(object.galleryId!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, pathOffset);
          fbb.addBool(2, object.isVideo);
          fbb.addFloat64(3, object.latitude);
          fbb.addFloat64(4, object.longitude);
          fbb.addOffset(5, addressOffset);
          fbb.addOffset(6, galleryIdOffset);
          fbb.addInt64(7, object.mediaStoreId);
          fbb.addInt64(8, object.width);
          fbb.addInt64(9, object.height);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final pathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final isVideoParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final latitudeParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final longitudeParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final galleryIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final mediaStoreIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final widthParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final heightParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final object = Media(
              path: pathParam,
              isVideo: isVideoParam,
              latitude: latitudeParam,
              longitude: longitudeParam,
              address: addressParam,
              galleryId: galleryIdParam,
              mediaStoreId: mediaStoreIdParam,
              width: widthParam,
              height: heightParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Photo] entity fields to define ObjectBox queries.
class Photo_ {
  /// See [Photo.id].
  static final id = obx.QueryIntegerProperty<Photo>(_entities[0].properties[0]);

  /// See [Photo.captureDate].
  static final captureDate =
      obx.QueryDateProperty<Photo>(_entities[0].properties[1]);

  /// See [Photo.galleryId].
  static final galleryId =
      obx.QueryStringProperty<Photo>(_entities[0].properties[2]);
}

/// [Media] entity fields to define ObjectBox queries.
class Media_ {
  /// See [Media.id].
  static final id = obx.QueryIntegerProperty<Media>(_entities[1].properties[0]);

  /// See [Media.path].
  static final path =
      obx.QueryStringProperty<Media>(_entities[1].properties[1]);

  /// See [Media.isVideo].
  static final isVideo =
      obx.QueryBooleanProperty<Media>(_entities[1].properties[2]);

  /// See [Media.latitude].
  static final latitude =
      obx.QueryDoubleProperty<Media>(_entities[1].properties[3]);

  /// See [Media.longitude].
  static final longitude =
      obx.QueryDoubleProperty<Media>(_entities[1].properties[4]);

  /// See [Media.address].
  static final address =
      obx.QueryStringProperty<Media>(_entities[1].properties[5]);

  /// See [Media.galleryId].
  static final galleryId =
      obx.QueryStringProperty<Media>(_entities[1].properties[6]);

  /// See [Media.mediaStoreId].
  static final mediaStoreId =
      obx.QueryIntegerProperty<Media>(_entities[1].properties[7]);

  /// See [Media.width].
  static final width =
      obx.QueryIntegerProperty<Media>(_entities[1].properties[8]);

  /// See [Media.height].
  static final height =
      obx.QueryIntegerProperty<Media>(_entities[1].properties[9]);
}
